### ISSUE TITLE
Firewall status not being updated due to execution order

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#114]
If you make a firewall change, the agent must run twice for the changes to be picked up in the interface. This is likely because we collect firewall status *before* we apply them.

**Comment by a-martynovich** [comment]
@vpetersson Please rename this task to smth like "Firewall changes order issue", we have another "race condition" task here.

**Comment by a-martynovich** [comment]
To do this we need to split the ping action in two. First: GET the instructions from the server (blocklist etc.). Second: apply them. Third: gather the info (including iptables state) and POST it to the server.
