### ISSUE TITLE
Permissions for credentials

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/agent#137]
*Needed by Screenly/screenly-ose#1149*
Currently `/opt/wott/credentials` is only accessible by root (`drwx------`) making it inaccessible for other apps such as Screenly.

This directory should be `drwx--x--x`. This means users can access files inside the directory, but can't list or modify them.

Credentials received from the server should have "owner" field (wottsecurity/api#272). Credentials records should be unique by owner-name-key. They should be grouped by owner (before grouping by name) and written to `/opt/wott/credentials/<owner>/<name>.json`. `/opt/wott/credentials/<owner>` should be owned by `<owner>` and have permissions `drwx------`. Files inside it should be owned by `<owner>` and  have permissions have permissions `dr--------`. 

If we had all credentials files under `/opt/wott/credentials` we would expose credentials for the following attack. An attacker tries  `/opt/wott/credentials/notexist.json` and gets "No such file", then tries  `/opt/wott/credentials/exists.json` and gets "Access Denied", meaning that this file exists. Now an attacker knows something he's not supposed to know, such that the file exists.

**Comment by vpetersson** [comment]
That's a point regarding the attack vector. I agree that we should adopt this model instead after reading this.

**Comment by eugenosm** [comment]
am I forgetting something?
![image](https://user-images.githubusercontent.com/35558969/59761061-a23aa900-92b5-11e9-9376-02f03a861972.png)

on fetch_credentials() it scans all credentials dir recursively. and remove all json files.
then sort all credentials by owner then by name
check if there such directories (as owners) in credentils path. if not creates that. if found something not dir with that name - exits with message.

if there no owner field or this is empty, such credentials placed in credentials folder and chowns to root

if some owner was not found in system, his files chowns to root

**Comment by a-martynovich** [comment]
Looks correct.
