### ISSUE TITLE
Switchable iptables policy

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/agent#139]
*Subtask of wottsecurity/api#255*
The server will send another item in `GET /api/ping`: "policy". When "policy" is "allow" everyhting stays as it is right now. 

When "policy" is "block":
* instead of "block_ports" the server will send "allow_ports" of the same format. These ports should be `-A INPUT ... -j ACCEPT`.
* INPUT policy should be switched to DROP.
* These rules should be added on top:
```
-A INPUT -i lo -j ACCEPT # +comment
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT # +comment
```

When policy is back to "allow" these rules should be removed and INPUT policy switched back to ACCEPT.

**Comment by rptrchv** [comment]
Drop 'firewall_enabled' parameter support from the agent code
