### ISSUE TITLE
Write documentation for how to use Kaa with WoTT

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#154]
[Kaa](https://www.kaaproject.org) is an IoT platform. There's an example [here](https://docs.kaaiot.io/Tutorials/docs/current/how-to-connect-device/) on how to connect a device using their Python client. 

Let's write out a documentation on how to use WoTT as the credential management for Kaa's token.

**Comment by vpetersson** [comment]
@rptrchv Please post what you got here from your research such that @fshmcallister can take over from there.

**Comment by rptrchv** [comment]
@fshmcallister Done:

- Run the Kaa sandbox (https://kaaproject.github.io/kaa/docs/v0.10.0/Getting-started/) in VirtualBox
- Setup Kaa server in my own Ubuntu 16.04 VM (https://kaaproject.github.io/kaa/docs/v0.10.0/Administration-guide/System-installation/Single-node-installation/)
- Played with this python client code (https://github.com/kaaproject/tutorials/blob/master/doc/how-to-connect-device/attach/code/client.py) but have not managed to make it connect to any application of Kaa sandbox or my own Kaa server
- Requested their cloud solution free demo access (was going to try to connect to it with my client code), but they didn't provide it yet
