### ISSUE TITLE
Write documentation for SiteWhere

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#158]
[SiteWhere](https://sitewhere.io/en/) is another IoT platform. They use Tokens for auth. Documentation can be found [here](https://sitewhere.io/docs/2.0.0/guide/devices/sending-data.html#sending-device-data).

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by AlEsmail** [comment]
Nope. Go for it :)
Have a look at the other documentation to get a feel for the style.
@fshmcallister has been handling documentation. Let her know if you have questions.

**Comment by MetalDent** [comment]
@AlEsmail okay thanks!
@fshmcallister hey, can you tell me where this info will go?

**Comment by fshmcallister** [comment]
Hi, if you refer to our main Agent page you will see an index of already written use cases and examples in our main README.
