### ISSUE TITLE
Add support for Raspbian Buster

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#185]
The Foundation has moved to Buster now and Jessie is no longer the default installation. We need to make the shift too and make sure the agent both works on Jessie and Buster.

**Comment by rptrchv** [comment]
on me


> The Foundation has moved to Buster now and Jessie is no longer the default installation. We need to make the shift too and make sure the agent both works on Jessie and Buster.

Jessie? Maybe Stretch?

**Comment by vpetersson** [comment]
Yes, sorry, I meant Stretch. We probably will need to add support for Jessie too at some point as it is still widely used.
