### ISSUE TITLE
Raspbian Jessie support

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/agent#199]
Jessie has Python 3.4. Agent is written for 3.5 and it will take a lot of time to rewrite it to 3.4.

In order to install 3.5 on Jessie we may either use pyenv or [deadsnakes ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+packages). The latter seems like an eaiser option. In order to use this ppa we need to add `deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu trusty main` to sources.list.

There're no prebuilt deb Python packages for 3.5 on Jessie, so we have to install all packages with pip. To do this we install pip from the older python:
`apt-get install python3-pip`
and then use it with 3.5:
```
python3.5 -m pip install --upgrade pip
python3.5 -m pip install --upgrade setuptools
python3.5 -m pip install -r requirements.txt
```

This will require build-essential, libsystemd-dev, pkg-config and probably some other packages.

Installing dev libraries and compilers is not a good behavior for a python-only package, so there is another option. We can pre-build packages which require compiling into deb packages and push them to our PPA. The python-only packages will still get installed by pip. It is important to name deb packages differently from the same packages of Debian, e.g. `python3.5-systemd` instead of `python3-systemd` to let Jessie apps continue working with the old Python.

**Comment by vpetersson** [comment]
Let's take the path of least resistance right now, which I assume is using the PPA. I'm not exactly excited about using a PPA that isn't supported by the upstream Debian team (I assume), but let's do that for the time being for older versions.

**Comment by a-martynovich** [comment]
Sorry, I forgot to mention that we don't have to use their PPA, we can download the needed packages and push them to our PPA, it will work.

The rest still applies.

**Comment by vpetersson** [comment]
Yeah, but we still don't know how these were built etc so there's still a liability issue there.

**Comment by a-martynovich** [comment]
We do know. That’s the whole purpose of Launchpad. You can get all the sources. We can’t build this ourselves because of CircleCI cross-compilation issue

**Comment by vpetersson** [comment]
Alright - user your best judgement.

**Comment by vpetersson** [comment]
That's a fair point. Should we just fork it?

**Comment by a-martynovich** [comment]
We can of course fork it, but how do we deal with distribution of packages? Do we collect them from Launchpad and push to PackageCloud or leave them on Launchpad?

**Comment by a-martynovich** [comment]
I've just tried using commands provided by "Add Device" on a fresh Jessie install on Pi 3B. Everything went flawlessly, and it even didn't require reboot.
