### ISSUE TITLE
Audit security posture of OpenSSH

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#207]
OpenSSH is likely one of the most common services to run on an edge device. Getting security right for OpenSSH isn't very hard, but it's easy to miss.

Let's add an audit feature that ensures that the configuration is secure.

Here are the values that we should check and warn if detected:

| Configuration  | Bad Value | Warning Type | Comment | 
| ------------- |:-------------:| -----:| -----:|
| PermitEmptyPasswords | yes | Severe | This is pretty bad.
| PermitRootLogin | yes | Severe | |
| Protocol | 2, 1 or 1 | Warning | There little reason for this to be 1 | 
| PasswordAuthentication | yes | Severe | Users should only use key based authentication |
| AllowAgentForwarding | yes | Warning | This is not ideal as it can be intercepted

We should look for the SSH config in some common locations, such as `/etc/ssh/sshd_config`.

**Comment by vpetersson** [comment]
I also want to display the following data in the dashboard:

 * The last modification date of the sshd_config
 * The sha256 hash of the file

**Comment by rptrchv** [comment]
Why password authentication is not secure?

**Comment by vpetersson** [comment]
Passwords can be brute forced. That's why it's generally considered more secure to use keys.
