### ISSUE TITLE
Collect and submit installed system packages

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#209]
As part of api#382, we need to know all installed (system) packages on a given device. We should probably submit this every day (not more frequently than that). 

It would be helpful to also think about caching to make sure that we don't submit it unless the actual list changes (e.g. we could sort and just hash the list and just compare that to the previous run).

**Comment by vpetersson** [comment]
@a-martynovich This should be closed out, right?

**Comment by vpetersson** [comment]
@a-martynovich This should be closed out, right?

**Comment by a-martynovich** [comment]
@vpetersson sure, I suppose there's this is a duplicate for some issue which was closed long ago.

**Comment by vpetersson** [comment]
Most likely, yes. Closing out.
