### ISSUE TITLE
Add support for Ubuntu 18.04

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#217]
We should now support:

* Debian 8/9
* Ubuntu 14.04/16.04

We are however missing support for Ubuntu 18.04.

**Comment by a-martynovich** [comment]
To support 18.04 we need to add `python3-distutils` to the dependency list and build the package separately. Same for Buster.

**Comment by a-martynovich** [comment]
@vpetersson  This is a duplicate of #211.

**Comment by vpetersson** [comment]
Closing out in favor of #211.
