### ISSUE TITLE
Add support for Amazon Linux

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#250]
We've had requests for adding support for [Amazon Linux](https://aws.amazon.com/amazon-linux-2/) in the agent. While Amazon is pitching it as a separate distro, it's CentOS/Fedora derived from the start, meaning that it's using RPM packages.

The starting point would be to build out CentOS support and then make sure these package also work on Amazon Linux.

More data:
* [What Linux distribution is the Amazon Linux AMI based on?](https://serverfault.com/questions/798427/what-linux-distribution-is-the-amazon-linux-ami-based-on)

**Comment by a-martynovich** [comment]
@vpetersson where do we push RPM packages (PackageCloud?) and how do we install them on Amazon Linux?

**Comment by vpetersson** [comment]
> where do we push RPM packages (PackageCloud?) and how do we install them on Amazon Linux?

Yes, PackageCloud should support this already. With regards on how to install it, we will need to alter the bash script. I've already prepared it for detection. 

> Also, there's Amazon Linux AMI and there's Amazon Linux 2. Which shall we support?

I believe it's Amazon Linux 2, but we have a meeting tonight and I will probe then.

**Comment by a-martynovich** [comment]
> With regards on how to install it, we will need to alter the bash script. I've already prepared it for detection.

Please provide the command you intend to use so that I could use it too

**Comment by vpetersson** [comment]
> Please provide the command you intend to use so that I could use it too.

`yum install wott-agent`? Been a while since i touched RHEL/CentOS-style systems.

> Also are we allowed to use EPEL?

No.  That will not pass most companies security checks for production.

**Comment by vpetersson** [comment]
Focus is Amazon Linux 2.

**Comment by vpetersson** [comment]
@rptrchv please claim this ticket since you're working on it.
