### ISSUE TITLE
Add environment/cloud detection

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#260]
I want to add detection of the following cloud environment into the agent:

* Google Cloud
* AWS
* Azure

This will then turn into tags in the dashboard.

**Comment by a-martynovich** [comment]
* Amazon EC2:
  * `/sys/devices/virtual/dmi/id/bios_version` should be `x.x.amazon`
  * `sys/hypervisor/uuid` should start with `ec2....`
  * `/sys/devices/virtual/dmi/id/product_uuid` should start with `EC2...`

**Comment by a-martynovich** [comment]
Fun fact: we can detect in which cloud environment a Docker container is running by reading  `/sys/devices/virtual/dmi/id/bios_version` in the container (`/sys` is probably mounted from the host).

**Comment by a-martynovich** [comment]
For Azure, there's [one way](https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceAzure.py#L1477-L1479
) which I think may work, but still not sure.
`dmidecode` relevant info:
```
Handle 0x0003, DMI type 3, 17 bytes
Chassis Information
        Manufacturer: Microsoft Corporation
        Type: Desktop
        Lock: Not Present
        Version: 7.0
        Serial Number: 5896-1832-4950-6629-8840-2285-25
        Asset Tag: 7783-7084-3265-9085-8269-3286-77
        Boot-up State: Safe
        Power Supply State: Safe
        Thermal State: Other
        Security Status: Other
        OEM Information: 0x00000000
```
We should be looking for `Asset Tag: 7783-7084-3265-9085-8269-3286-77`
