### ISSUE TITLE
Detect and send kernel metapacakages

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/agent#268]
Add new fields to ping: `kernel_metapackage` and `kernel_headers_metapackage`. Detect them as follows.

Let's say the currently running kernel is in `linux-image-4.15.0-1060-aws`. Another package, `linux-image-aws`, depends on it. Another package, `linux-aws`, depends on `linux-image-aws`. Dependency chain: `linux-aws => linux-image-aws => linux-image-4.15.0-1060-aws`. I believe nothing depends on `linux-aws` (need to double-check). `linux-aws` is the kernel meta-package.

`linux-headers-4.15.0-1060-aws` is listed as a recommendation for  `linux-image-4.15.0-1060-aws`. Dependency chain: `linux-headers-aws => linux-headers-4.15.0-1060-aws => linux-aws-headers-4.15.0-1060`. `linux-headers-aws` is a meta-package.

**Comment by vpetersson** [comment]
Related to https://github.com/WoTTsecurity/api/issues/715
