### ISSUE TITLE
Create native debian packaging

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#34]
There are benefits with the Snap packaging platform. However, it also comes with a lot of drawbacks. To move faster, we should move to native Debian packaging as it gives us less restrictions.

Here are some requirements:

 * We need to be able to build these packages in a build farm
 * We need to provide multiple architectures

One solution is Ubuntu's Launchpad with their PPAs. Another alternative is [packagecloud](https://www.packagecloud.io/).

**Comment by vpetersson** [comment]
Here are some additional resources:

 * [Creating a Debian Package](https://debian-handbook.info/browse/stable/debian-packaging.html)
 * [fpm](https://github.com/jordansissel/fpm)

**Comment by a-martynovich** [comment]
Here's what I did to build ghostunnel in a debian docker container:

    dpkg --add-architecture armel
    apt-get update
    apt-get install crossbuild-essential-armel libltdl-dev:armel
    wget https://dl.google.com/go/go1.12.3.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.12.3.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin

And then, simply checkout ghostunnel source and

    GOARM=6 GOOS=linux GOARCH=arm go build

**Comment by vpetersson** [comment]
Let's make that part of the CI workflow and build it on Circle CI.
