### ISSUE TITLE
Create post installation for deb package

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#39]
The Debian package should do the following things:

 * Run `wott-agent` to initiate the package
 * Print out a post-installation message

## Post installation message

```
Thank you for installing the wott-agent. Your device's unique ID is: [device id]

To unleash the value of WoTT, and to gain insight into the security of your device(s), sign up for an account at http://dash.wott.io.

You can claim your device in the dashboard by visiting:
[device claim URL]

For more information on how to get started, visit wott.io/getting-started
```

**Comment by AlEsmail** [comment]
Good job installing the wott-agent and welcome to the community of security conscious hardware devs! 

You're one step closer to building a secure device. Your device's unique ID is: [device id]

To unleash the value of WoTT, and to gain insight into the security of your device(s), connect your device at https://dash.wott.io.

You can claim your device in the dashboard by visiting:
[device claim URL]

For more information on how to get started, visit wott.io/getting-started or drop me a line at hey@wott.io.

Best!
Viktor

**Comment by vpetersson** [comment]
Works, but I wouldn't sign it off with my name as it is a message from the team.

**Comment by a-martynovich** [comment]
@vpetersson How about we let this message be produced by agent, not by postinstall script? The script will just invoke agent (with some `--arg` if needed). This way it will be a lot simpler.

Otherwise I'll have to extract deviceId and claimURL to put them in the message. That's ugly and will break in the future.

**Comment by vpetersson** [comment]
@a-martynovich Yeah that's fine by me.

**Comment by a-martynovich** [comment]
This issue  depends on #44 now.
