### ISSUE TITLE
Fix systemd timer in deb package

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#41]
After installing the new debian package, we are missing the systemd timer:

```
$ sudo  systemctl list-timers
NEXT                         LEFT          LAST                         PASSED       UNIT                         ACTIVATES
Tue 2019-04-16 19:03:51 BST  4h 19min left Tue 2019-04-16 11:55:45 BST  2h 48min ago snapd.refresh.timer          snapd.refresh.service
Wed 2019-04-17 05:06:48 BST  14h left      Tue 2019-04-16 13:37:45 BST  1h 6min ago  apt-daily.timer              apt-daily.service
Wed 2019-04-17 06:48:56 BST  16h left      Tue 2019-04-16 06:59:10 BST  7h ago       apt-daily-upgrade.timer      apt-daily-upgrade.service
Wed 2019-04-17 11:28:45 BST  20h left      Tue 2019-04-16 11:28:45 BST  3h 15min ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service

4 timers listed.
Pass --all to see loaded but inactive timers, too.
```

**Comment by a-martynovich** [comment]
@vpetersson I previously said the timer only activates after reboot. That's not true, it's just the debhelper logic is flawed: if the package was previously installed the timer is not started, it is instead re-started. But if the previously installed package didn't have any timers there's nothing to restart, so nothing happens.

To avoid this, you need to remove all of the package remains  with `sudo apt remove --purge wott-agent`. Next time you install the package the timer will be started at once.
