### ISSUE TITLE
Auto-bump deb version 

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/agent#51]
If CircleCI is building master branch it should run the script which bumps the version before building deb package.
The script should parse the latest debian/changelog record looking for commit hash. If found, it should create another record with all commits messages since the said commit, a bumped version and the latest commit hash.

```
wott-agent (<RELEASE_VERSION>+ppa<COUNTER>) stable; urgency=medium

  Built from commit <hashhashhash>.
  * Commit one <hashhashhash>
  * Commit two <hashhashhash>
  <...>

 -- WoTT <developer@wott.io>  Sat, 1 Apr 2019 00:00:00 +0000
```

**Comment by vpetersson** [comment]
@a-martynovich merging this into #96 instead. How we do the link between the two is tbd but i want to couple them.

**Comment by a-martynovich** [comment]
@vpetersson It should be a subtask of #96 or something.
But. This task has its main purpose: to prevent master builds from failing because it can't push the deb package to PackageCloud. This task also has a solution. So it has to be done first.

#96 is tbd so it can wait.

**Comment by vpetersson** [comment]
@a-martynovich fair point - yes - those are two different things, but if we use for instance the short hash as part of the number we would get around that package cloud issue too.
