### ISSUE TITLE
Enable the ability to "force run" the wott-agent to report in data.

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#91]
It is sometime useful to "force push" status for a device when you are experimenting. Hence, even after we've converted the agent from a cronjob (or timer) in #35, we still need to be able to run a CLI command to speed things up.

**Comment by a-martynovich** [comment]
@vpetersson You can still run `sudo wott-agent` to push the data immediately.
No extra coding required.

**Comment by vpetersson** [comment]
Got it. Cool.
