### ISSUE TITLE
Don't display post-installation instruction if claimed

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#94]
Let's differentiate between a claimed and unclaimed device in the post-installation instructions. If the device has already been claimed, there is no need to display the message about claiming.

**Comment by a-martynovich** [comment]
@vpetersson AFAIK the only case when the device is already claimed is if it had the agent already installed (and its config files and certs therein).

Am I missing something and do we need to ask the server if the device had already been claimed?

**Comment by vpetersson** [comment]
What I'm talking about is if you run `apt-get upgrade` and install an updated version of the agent. We then get the same message again about how to claim the device (despite that it has already been claimed)

> Am I missing something and do we need to ask the server if the device had already been claimed?

Yes, I think that's the only way.

**Comment by a-martynovich** [comment]
**clarification:**
* When `wott-agent claim-url` is called, check if the device is already claimed by getting `/api/.../is-claimed` (wottsecurity/api#206) and if it is, return empty string.
* Update postinst.

@vpetersson do we need the postinst message at all when upgrading? It's all about getting started and claiming: https://github.com/WoTTsecurity/agent/blob/master/debian/postinst#L4-L13

**Comment by vpetersson** [comment]
We probably do not need it at all, to be honest. We do however need to know the claim status in the agent.

**Comment by a-martynovich** [comment]
@vpetersson So the postinst message should be completely removed, right?

> We do however need to know the claim status in the agent.

My idea is that if the device is already claimed `wott-agent claim-url` returns empty. The url isn't valid anyway in this case.

**Comment by vpetersson** [comment]
Yeah sure, or an error saying 'Device already claimed' or similar.

**Comment by eugenosm** [comment]
i'll take it
